AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.1

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/AbcSize:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false
