version: 1
jobs:
  build:
    working_directory: ~/Authenticator-ruby-gem
    docker:
      - image: circleci/ruby:2.5.0-node
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Run tests
          command: rspec
      - run:
          name: Run Rubocop
          command: rubocop