name: Volcanic Authenticator build

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}:x-oauth-basic
        with:
          ruby-version: '2.5'
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
      - name: Spec
        run: bundle exec rake

